# The Python Programming Language

From Coursera: Intro to Data Science, Week 1   
Patricia Schuster, University of Michigan  
Feb. 2017

# Numpy

Today we will be using numpy, which allows us to work efficiently with arrays and matrices in python. 

Start by importing numpy

In [1]:
import numpy as np

## Numpy arrays

Create an array. We can start by creating a list and then converting it to an array.

In [2]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

But you can also pass in the list directly.

In [4]:
y = np.array([4,5,6])
y

array([4, 5, 6])

We can make two-dimensional arrays by passing in a list of lists.

In [6]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

`numpy` arrays have a useful built-in function called `shape`.

In [7]:
m.shape

(2, 3)

Other useful `numpy` functions are:

* `resize()`
* `np.ones()`
* `np.zeros()`
* `np.eye()`
* `np.diag()`
* `np.repeat()`
* `np.vstack`
* `np.hstack`

## Operations

Straight-forward operations include addition, subtraction, powers. 

In [8]:
x

array([1, 2, 3])

In [9]:
x**2

array([1, 4, 9])

In [10]:
x.dot(y)

32

In [13]:
z =np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [14]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [15]:
z.sum()

92

In [16]:
z.min()

4

In [17]:
z.std()

11.855612829185826

## Indexing / slicing

This works similarly to how it works with strings.

In [23]:
x = np.arange(12)**2
x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [21]:
x[4]

16

In [22]:
x[4:]

array([ 16,  25,  36,  49,  64,  81, 100, 121, 144])

In [26]:
x = x.reshape(4,3)

In [30]:
x

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [31]:
x[3,2]

121

In [32]:
x[2:,1:]

array([[ 49,  64],
       [100, 121]])

In [33]:
x[2,:]

array([36, 49, 64])

In [34]:
x.copy()

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

# Iterating over arrays

In [36]:
test = np.random.randint(0,10,(4,3))
test

array([[3, 8, 9],
       [6, 4, 9],
       [0, 8, 2],
       [4, 9, 5]])

In [38]:
for row in test:
    print(row)

[3 8 9]
[6 4 9]
[0 8 2]
[4 9 5]


In [40]:
for i in range(len(test)):
    print(test[i])

[3 8 9]
[6 4 9]
[0 8 2]
[4 9 5]


If we want to iterate through two arrays, we can use zip.

In [41]:
test2 = test**2
test2

array([[ 9, 64, 81],
       [36, 16, 81],
       [ 0, 64,  4],
       [16, 81, 25]])

In [42]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[3 8 9] + [ 9 64 81] = [12 72 90]
[6 4 9] + [36 16 81] = [42 20 90]
[0 8 2] + [ 0 64  4] = [ 0 72  6]
[4 9 5] + [16 81 25] = [20 90 30]
